//ExploreのView
Ext.define("picasa.view.ExploreView", {
  extend:'Ext.Container',
  xtype:'exploreview',
  requires:[
    'Ext.field.Search'
  ],
  config:{
    scrollable:{
      direction: 'vertical',
      directionLock: true
    },
    layout:'vbox',
    items:[
      {
        html:'<h2>Featured</h2>',
        cls:'h2title'
      },
      {
        xtype:'featurephoto',
        scrollable:false
      },
      {
        html:'<h2>Popular</h2>',
        cls:'h2title'
      },
      {
        xtype:'searchfield',
        placeHolder:'search',
        cls:'picasaSearch'
      },
      {
        scrollable:false,
        cls:'searchTags',
        items:[
          {
            xtype:'button',
            text:'italy',
            action:'tag',
            cls:'searchTag'
          },
          {
            xtype:'button',
            text:'new',
            action:'tag',
            cls:'searchTag'
          },
          {
            xtype:'button',
            text:'flowers',
            action:'tag',
            cls:'searchTag'
          },
          {
            xtype:'button',
            text:'pics',
            action:'tag',
            cls:'searchTag'
          },
          {
            xtype:'button',
            text:'Jazz',
            action:'tag',
            cls:'searchTag'
          },
          {
            xtype:'button',
            text:'NewYork',
            action:'tag',
            cls:'searchTag'
          },
          {
            xtype:'button',
            text:'Cars2',
            action:'tag',
            cls:'searchTag'
          },
          {
            xtype:'button',
            text:'Curry',
            action:'tag',
            cls:'searchTag'
          },
          {
            xtype:'button',
            text:'MacBook',
            action:'tag',
            cls:'searchTag'
          }
        ]
      }
    ]
  },

  initialize:function () {
    this.callParent(arguments);
  }
});
