Ext.define("picasa.view.Main", {
  extend:'Ext.tab.Panel',
  requires:[
  ],
  config:{
    tabBarPosition:'top',
    items:[
      {
        xtype:'toolbar',
        docked:'top',
        itemId:'picasaToolbar',
        title:'My Picasa',
        items:[
          {
            xtype:'spacer'
          },
          {
            itemId:'refreshButton',
            iconCls:'refresh',
            iconMask:true,
            ui:'plain'
          }
        ]
      },
      {
        title:'Featured',
        xtype:'featureview'
      },
      {
        title:'Album',

        items:[
          {
            html:'hhhhhhhh'
          }
        ]
      }
    ]
  }
});
