/*
 * File: app/view/TweetList.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Afc.view.TweetList', {
    extend: 'Ext.Container',
    alias: 'widget.tweetlist',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'searchfield',
                        label: ''
                    },
                    {
                        xtype: 'button',
                        cls: '',
                        ui: 'plain',
                        iconCls: 'refresh',
                        iconMask: true,
                        text: ''
                    }
                ]
            },
            {
                xtype: 'list',
                itemTpl: [
                    '<div><span class="text">{text}</span><span class="date">{created_at:date("Y/m/d")}</span> </div>'
                ],
                store: 'Tweets'
            }
        ]
    }

});