Ext.define('docomo.model.Match', {
  extend:'Ext.data.Model',
  config:{
    fields:[
      {
        name:'date',
        type:'date',
        dateFormat:'Y/m/d'
      },
      {
        name:'home'
      },
      {
        name:'visitor'
      },
      {
        name:'score'
      }
    ]
  }
});