Ext.define('picasa.model.Album', {
  extend:'Ext.data.Model',
  config:{
    fields:[
      {
        name:'id',
        mapping:'gphoto$id.$t'
      },
      {
        name:'title',
        mapping:'title.$t'
      },
      {
        name:'link',
        mapping:'link[0].href'
      },
      {
        name:'date',
        mapping:'published.$t'
      },
      {
        name:'mediaThumbnail',
        mapping:'media$group.media$thumbnail[0]'
      },
      {
        name:'mediaContent',
        mapping:'media$group.media$content[0]'
      }
    ]
  }
});