Ext.define("docomo.view.TweetList", {
  extend:'Ext.Container',
  xtype:'tweetlist',
  requires:[
    'Ext.dataview.List',
    'Ext.field.Search',
    'Ext.Button'
  ],
  config:{
    layout:'fit',
    tabBarPosition:'bottom',
    items:[
      {
        xtype:'toolbar',
        docked:'top',
        items:[
          {
            xtype:'searchfield',
            placeHolder:'search'
          },
          {
            xtype:'button',
            iconCls:'refresh',
            iconMask:true,
            ui:'plain'
          }
        ]
      },
      {
        xtype:'list',
        store:'Tweets',
        itemTpl:'<div><span class="text">{text}</span><span class="date">{created_at:date("Y/m/d")}</span> </div>'
      }
    ]
  }
});
